version: '3.9'
services:
  db:
    image: mysql:8.0.29-debian
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - agmc
  api:
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: host.docker.internal
      DB_NAME: "${DB_NAME}"
      DB_PASS: "${DB_PASS}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - agmc
networks:
  agmc:
    driver: bridge
volumes:
  db:
    external: false